pub mod file_ops;
pub mod system_logs;
pub mod memory_ops;
pub mod network_ops;
pub mod registry_ops;
pub mod timestamp_ops;
pub mod anti_analysis_ops;
pub mod scan_ops;
pub mod disk_encryption_ops;
pub mod system_info_ops;
pub mod permission_ops;
pub mod settings_ops;
pub mod scheduled_ops;
pub mod platform_ops;
pub mod cleanup_ops;
pub mod license_ops;

pub use file_ops::{secure_delete_file, get_file_info};
pub use system_logs::{clear_system_logs, get_platform, scan_system_logs};
pub use memory_ops::{clean_memory, get_memory_info, scan_memory_items, get_detailed_memory_info, get_top_processes};
pub use network_ops::{clean_network, get_network_info, scan_network_items};
pub use registry_ops::clean_registry;
pub use timestamp_ops::{get_file_timestamps, modify_file_timestamps};
pub use anti_analysis_ops::check_environment;
pub use scan_ops::{perform_system_scan, cleanup_scan_items};
pub use disk_encryption_ops::{check_disk_encryption, enable_disk_encryption, disable_disk_encryption, get_encryption_recommendations};
pub use system_info_ops::{get_system_info_api, get_network_speed_api, get_disks_info_api};
pub use permission_ops::{check_admin_permission, get_elevation_guide, requires_admin, request_admin_elevation, open_privacy_settings};
pub use settings_ops::{save_settings, load_settings, reset_settings, get_settings_info};
pub use scheduled_ops::{get_scheduled_tasks, get_scheduled_task_by_id, create_scheduled_task, update_scheduled_task_cmd, delete_scheduled_task, toggle_scheduled_task, get_custom_rules, get_custom_rule_by_id, create_custom_rule, update_custom_rule_cmd, delete_custom_rule, toggle_custom_rule, get_rule_templates_cmd, get_pending_scheduled_tasks};
pub use platform_ops::{get_platform_info, get_linux_distro_info, check_feature_available, get_feature_reason, get_running_operations, cancel_running_operation, cancel_all_running_operations, get_timeout_settings, set_timeout_settings, get_cpu_info, check_features};
pub use cleanup_ops::{perform_app_self_clean, get_app_traces_info, preview_deletion, preview_log_clean, preview_browser_clean, preview_shell_clean, preview_dns_clean, preview_trash_clean, preview_all_cleanup};
pub use license_ops::{get_machine_id, get_full_machine_id, get_license_status, validate_license, activate_license, deactivate_license, get_feature_access, can_access_feature, is_pro_user};
