pub mod command_utils;
pub mod windows_utils;
pub mod secure_delete;
pub mod log_cleaner;
pub mod memory_cleaner;
pub mod network_cleaner;
pub mod registry_cleaner;
pub mod timestamp_modifier;
pub mod anti_analysis;
pub mod disk_encryption;
pub mod system_info;
pub mod permission;
pub mod settings_storage;
pub mod path_validator;
pub mod error_handling;
pub mod timeout_handler;
pub mod scheduled_cleanup;
pub mod performance;
pub mod self_cleaning;
pub mod secure_memory;
pub mod dry_run;
pub mod license;
pub mod license_validator;
pub mod license_storage;

pub use secure_delete::{WipeMethod, secure_delete, secure_delete_with_progress};
pub use log_cleaner::clear_system_logs;
pub use memory_cleaner::{MemoryInfo, clean_memory, get_memory_info};
pub use network_cleaner::clean_network;
pub use registry_cleaner::clean_registry;
pub use timestamp_modifier::{FileTimestamps, get_file_timestamps, modify_file_timestamps};
pub use anti_analysis::{EnvironmentCheck, check_environment};
pub use system_info::{SystemInfo, NetworkSpeed, DiskInfo, get_system_info, get_network_speed, get_disks_info};
pub use permission::{is_elevated, get_elevation_guide, requires_elevation, open_privacy_settings};
pub use settings_storage::{AppSettings, SettingsDbInfo, save_all_settings, load_all_settings, reset_all_settings, get_settings_db_info};
pub use path_validator::{PathValidator, PathValidationError, validate_file_path, validate_directory_path, validate_path, is_safe_for_deletion, sanitize_filename};
pub use error_handling::{OperationError, ErrorCode, OperationLog, OperationType, OperationStatus, PlatformCapabilities, LinuxDistro, FeatureCapability, get_platform_capabilities, detect_linux_distro, is_feature_available, get_feature_unavailable_reason};
pub use timeout_handler::{CancellationToken, OperationHandle, OperationInfo, TimeoutConfig, ProgressUpdate, cancel_operation, cancel_all_operations, get_active_operations, get_timeout_config, set_timeout_config};
pub use scheduled_cleanup::{ScheduleFrequency, ScheduledTask, CleanupAction, TaskResult, CustomRule, RuleType, RulePattern, RuleAction, add_scheduled_task, get_scheduled_task, get_all_scheduled_tasks, remove_scheduled_task, update_scheduled_task, get_pending_tasks, add_custom_rule, get_custom_rule, get_all_custom_rules, remove_custom_rule, update_custom_rule, get_rule_templates};
pub use performance::{get_cpu_count, get_physical_cpu_count, configure_thread_pool, DeletionProgress, scan_directory_parallel, delete_files_parallel, delete_directory_parallel, batch_operation, BatchResult};
pub use self_cleaning::{SelfCleanResult, get_app_cache_paths, get_temp_files, clean_app_cache, clean_webview_data, perform_self_cleaning, get_app_traces_size};
pub use secure_memory::{SecureString, SecureBytes, SecureBuffer, SecureContext, SensitiveGuard, secure_random_bytes, secure_clear, secure_clear_string};
pub use dry_run::{DryRunOperation, PreviewItem, RiskLevel, PreviewResult, preview_file_deletion, preview_log_cleaning, preview_browser_cleaning, preview_shell_history_cleaning, preview_dns_flush, preview_trash_cleaning, preview_full_cleanup};
pub use license::{LicenseTier, LicenseStatus, LicenseValidationResult, ActivatedLicense, FeatureAccess};
pub use license_validator::{get_machine_id, get_short_machine_id, validate_license_key, generate_license_key};
pub use license_storage::{get_license_status, activate_license, deactivate_license, get_feature_access, can_access_feature};
pub use command_utils::{command, execute, execute_string, CommandExt};
